### ISSUE TITLE
Windows Powershell 7 issue creating component

### ISSUE THREAD

**Issue by lars-zweifel** [mmssolutionsio/mms-reporting-library#10]
## Expected Behavior
Creating a component in a selected group

## Current Behaviour 
Exception `SyntaxError: Invalid regular expression: /\/gi: \ at end of pattern`
It seems to try and write into the wrong directory (livingdocs/livingdocs/...)

## Context (Environment)
Windows 11 
Powershell 7 x64 
Node v22.6.0 | npm 10.8.2

## Detailed Description
```PS D:\nhs\test-reportinglibrary\TESTDesugn01> npx nswow create component my-component
√ Group · livingdocs\my-group
Error: ENOENT: no such file or directory, mkdir 'D:\nhs\test-reportinglibrary\TESTDesugn01\livingdocs\livingdocs\my-group'
    at mkdirSync (node:fs:1363:26)
    at writeComponent (file:///D:/nhs/test-reportinglibrary/TESTDesugn01/node_modules/@multivisio/nswow/scripts/components.js:326:19)
    at file:///D:/nhs/test-reportinglibrary/TESTDesugn01/node_modules/@multivisio/nswow/scripts/components.js:434:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\nhs\\test-reportinglibrary\\TESTDesugn01\\livingdocs\\livingdocs\\my-group'
}```

**Comment by mikedoerer** [comment]
Ok, schaue ich mir an.
